name: .NET

on:
  workflow_dispatch:
    inputs:
      relName:
        description: 'Release Name'
        required: true
env:
  solution_path: "./Source/Microsoft.Teams.Apps.FAQPlusPlus.sln"
  faqpluplus_path: "./Source/Microsoft.Teams.Apps.FAQPlusPlus/Microsoft.Teams.Apps.FAQPlusPlus.csproj"  
  FAQPlusPluspublish_path: "/home/runner/work/microsoft-teams-apps-faqplus/microsoft-teams-apps-faqplus/Source/Microsoft.Teams.Apps.FAQPlusPlus/bin/Release/netcoreapp2.1/publish"
  azurefunc_path: "./Source/Microsoft.Teams.Apps.FAQPlusPlus.AzureFunction/Microsoft.Teams.Apps.FAQPlusPlus.AzureFunction.csproj"
  FAQPlusPlusFuncpublish_path: "/home/runner/work/microsoft-teams-apps-faqplus/microsoft-teams-apps-faqplus/Source/Microsoft.Teams.Apps.FAQPlusPlus.AzureFunction/bin/Release/netcoreapp2.1/publish"
jobs:
  build_faqplusplusfunc:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - name: Setup .NET
       uses: actions/setup-dotnet@v1
       with:
        dotnet-version: 2.1.515
     - name: Restore dependencies
       run: dotnet restore "${{env.azurefunc_path}}"
     - name: Build
       run: dotnet build "${{env.azurefunc_path}}" --no-restore --configuration Release
     - name: Publish
       run: dotnet publish "${{env.azurefunc_path}}" --configuration Release --no-restore --no-build
    
     - uses: actions/upload-artifact@v2
       with:
        name: FAQPlusPlus
        path: ${{env.FAQPlusPlusFuncpublish_path}}

     - name: Zip project
       run: |
        cd $FAQPlusPlusFuncpublish_path/ && zip -r FAQPlusPlusFunc.zip *
        
     
  build_faqpluplus:
    runs-on: ubuntu-latest
    needs: build_faqplusplusfunc
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.515
    - name: Restore dependencies
      run: dotnet restore "${{env.faqpluplus_path}}"
    - name: Build
      run: dotnet build "${{env.faqpluplus_path}}" --no-restore --configuration Release
    - name: Publish
      run: dotnet publish "${{env.faqpluplus_path}}" --configuration Release --no-restore --no-build
    
    - uses: actions/upload-artifact@v2
      with:
        name: FAQPlusPlus
        path: ${{env.FAQPlusPluspublish_path}}
   
    - name: Build project # This would actually build your project, using zip for an example artifact
      run: |
        cd $FAQPlusPluspublish_path/ && zip -r FAQPlusPlus.zip *            
    

  upload_relrase:
    - name: Create Release
       id: create_release
       uses: actions/create-release@v1
       env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       with:
        tag_name: ${{ github.event.inputs.relName }}
        release_name: Release ${{ github.event.inputs.relName }}
        draft: false
        prerelease: false
    
     - name: Upload FAQPlusPlusFunc Release Asset
       id: upload-release-asset 
       uses: actions/upload-release-asset@v1
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ${{env.FAQPlusPlusFuncpublish_path}}/FAQPlusPlusFunc.zip
        asset_name: FAQPlusPlusFunc.zip
        asset_content_type: application/zip

     - name: Upload FAQPlusPlus Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ${{env.FAQPlusPluspublish_path}}/FAQPlusPlus.zip
          asset_name: FAQPlusPlus.zip
          asset_content_type: application/zip 
    
